name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          cache: 'npm'
      - run: |
          npm ci
          npm run lint
          npm run format-check
          npm run test
          npm run build
        env:
          CI: true
